const messageTypeEnum = {
  //Spielinitialisierung
  HELLO: "HELLO",
  HELLO_REPLY: "HELLO_REPLY",
  RECONNECT: "RECONNECT",
  GAME_STARTED: "GAME_STARTED",
  // Wahlphase
  REQUEST_ITEM_CHOICE: "REQUEST_ITEM_CHOICE",
  ITEM_CHOICE: "ITEM_CHOICE",
  REQUEST_EQUIPMENT_CHOICE: "REQUEST_EQUIPMENT_CHOICE",
  EQUIPMENT_CHOICE: "EQUIPMENT_CHOICE",
  // Spielphase
  GAME_STATUS: "GAME_STATUS",
  REQUEST_GAME_OPERATION: "REQUEST_GAME_OPERATION",
  GAME_OPERATION: "GAME_OPERATION",
  // Spielende
  STATISTICS: "STATISTICS",
  // Kontrollnachrichten
  GAME_LEAVE: "GAME_LEAVE",
  GAME_LEFT: "GAME_LEFT",
  REQUEST_GAME_PAUSE: "REQUEST_GAME_PAUSE",
  GAME_PAUSE: "GAME_PAUSE",
  REQUEST_META_INFORMATION: "REQUEST_META_INFORMATION",
  META_INFORMATION: "META_INFORMATION",
  STRIKE: "STRIKE",
  ERROR: "ERROR",
  // Optionale Komponenten
  REQUEST_REPLAY: "REQUEST_REPLAY",
  REPLAY: "REPLAY",
};

const roleEnum = {
  SPECTATOR: "SPECTATOR",
  PLAYER: "PLAYER",
  AI: "AI",
};

const propertyEnum = {
  NIMBLENESS: "NIMBLENESS",
  SLUGGISHNESS: "SLUGGISHNESS",
  PONDEROUSNESS: "PONDEROUSNESS",
  SPRYNESS: "SPRYNESS",
  AGILITY: "AGILITY",
  LUCKY_DEVIL: "LUCKY_DEVIL",
  JINX: "JINX",
  CLAMMY_CLOTHES: "CLAMMY_CLOTHES",
  CONSTANT_CLAMMY_CLOTHES: "CONSTANT_CLAMMY_CLOTHES",
  ROBUST_STOMACH: "ROBUST_STOMACH",
  TOUGHNESS: "TOUGHNESS",
  BABYSITTER: "BABYSITTER",
  HONEY_TRAP: "HONEY_TRAP",
  BANG_AND_BURN: "BANG_AND_BURN",
  FLAPS_AND_SEALS: "FLAPS_AND_SEALS",
  TRADECRAFT: "TRADECRAFT",
  OBSERVATION: "OBSERVATION",
};

const gadgetEnum = {
  HAIRDRYER: "HAIRDRYER",
  MOLEDIE: "MOLEDIE",
  TECHNICOLOUR_PRISM: "TECHNICOLOUR_PRISM",
  BOWLER_BLADE: "BOWLER_BLADE",
  MAGNETIC_WATCH: "MAGNETIC_WATCH",
  POISON_PILLS: "POISON_PILLS",
  LASER_COMPACT: "LASER_COMPACT",
  ROCKET_PEN: "ROCKET_PEN",
  GAS_GLOSS: "GAS_GLOSS",
  MOTHBALL_POUCH: "MOTHBALL_POUCH",
  FOG_TIN: "FOG_TIN",
  GRAPPLE: "GRAPPLE",
  WIRETAP_WITH_EARPLUGS: "WIRETAP_WITH_EARPLUGS",
  DIAMOND_COLLAR: "DIAMOND_COLLAR",
  JETPACK: "JETPACK",
  CHICKEN_FEED: "CHICKEN_FEED",
  NUGGET: "NUGGET",
  MIRROR_OF_WILDERNESS: "MIRROR_OF_WILDERNESS",
  POCKET_LITTER: "POCKET_LITTER",
  ANTI_PLAGUE_MASK: "ANTI_PLAGUE_MASK",
  COCKTAIL: "COCKTAIL",
};

const operationEnum = {
  GADGET_ACTION: "GADGET_ACTION",
  SPY_ACTION: "SPY_ACTION",
  GAMBLE_ACTION: "GAMBLE_ACTION",
  PROPERTY_ACTION: "PROPERTY_ACTION",
  MOVEMENT: "MOVEMENT",
  CAT_ACTION: "CAT_ACTION",
  JANITOR_ACTION: "JANITOR_ACTION",
  EXFILTRATION: "EXFILTRATION",
  RETIRE: "RETIRE",
};

const errorEnum = {
  NAME_NOT_AVAILABLE: "NAME_NOT_AVAILABLE",
  ALREADY_SERVING: "ALREADY_SERVING",
  SESSION_DOES_NOT_EXIST: "SESSION_DOES_NOT_EXIST",
  ILLEGAL_MESSAGE: "ILLEGAL_MESSAGE",
  TOO_MANY_STRIKES: "TOO_MANY_STRIKES",
  GENERAL: "GENERAL",
};

const victoryEnum = {
  VICTORY_BY_IP: "VICTORY_BY_IP",
  VICTORY_BY_COLLAR: "VICTORY_BY_COLLAR",
  VICTORY_BY_DRINKING: "VICTORY_BY_DRINKING",
  VICTORY_BY_SPILLING: "VICTORY_BY_SPILLING",
  VICTORY_BY_HP: "VICTORY_BY_HP",
  VICTORY_BY_RANDOMNESS: "VICTORY_BY_RANDOMNESS",
  VICTORY_BY_LEAVE: "VICTORY_BY_LEAVE",
  VICTORY_BY_KICK: "VICTORY_BY_KICK",
};

const fieldStateEnum = {
  BAR_TABLE: "BAR_TABLE",
  ROULETTE_TABLE: "ROULETTE_TABLE",
  WALL: "WALL",
  FREE: "FREE",
  BAR_SEAT: "BAR_SEAT",
  SAFE: "SAFE",
  FIREPLACE: "FIREPLACE",
};

const genderEnum = {
  MALE: "MALE",
  FEMALE: "FEMALE",
  DIVERSE: "DIVERSE",
};

const phaseEnum = {
  INIT: "INIT",
  ITEM_CHOSE: "ITEM_CHOSE",
  EQUIP_CHOSE: "EQUIP_CHOSE",
  GAME: "GAME",
  END: "END",
};

const metaEnum = {
  CONFIG_SCENARIO: "Configuration.Scenario",
  CONFIG_MATCH: "Configuration.Matchconfig",
  CONFIG_CHAR: "Configuration.CharacterInformation",
  FRAC_ONE: "Fraction.Player1",
  FRAC_TWO: "Fraction.Player2",
  FRAC_NEUTRAL: "Fraction.Neutral",
  GAD_ONE: "Gadgets.Player1",
  GAD_TWO: "Gadgets.Player2",
};

module.exports = {
  messageTypeEnum,
  roleEnum,
  propertyEnum,
  gadgetEnum,
  operationEnum,
  errorEnum,
  victoryEnum,
  fieldStateEnum,
  genderEnum,
  phaseEnum,
  metaEnum,
};
